=begin
#NamSor API v2

#NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 1000 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 

OpenAPI spec version: 2.0.2-beta
Contact: contact@namsor.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for NamSorClient::SocialApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SocialApi' do
  before do
    # run before each test
    @api_instance = NamSorClient::SocialApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SocialApi' do
    it 'should create an instance of SocialApi' do
      expect(@api_instance).to be_instance_of(NamSorClient::SocialApi)
    end
  end

  # unit tests for phone_prefix
  # [USES 11 UNITS] Infer the likely country and phone prefix, given a personal name and formatted / unformatted phone number.
  # @param first_name 
  # @param last_name 
  # @param phone_number 
  # @param [Hash] opts the optional parameters
  # @return [FirstLastNamePhoneCodedOut]
  describe 'phone_prefix test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_prefix_batch
  # [USES 11 UNITS] Infer the likely country and phone prefix, of up to 1000 personal names, detecting automatically the local context given a name and formatted / unformatted phone number.
  # @param [Hash] opts the optional parameters
  # @option opts [BatchFirstLastNamePhoneNumberIn] :batch_first_last_name_phone_number_in A list of personal names
  # @return [BatchFirstLastNamePhoneCodedOut]
  describe 'phone_prefix_batch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
