=begin
#NamSor API v2

#NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 1000 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 

OpenAPI spec version: 2.0.2-beta
Contact: contact@namsor.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

# Common files
require 'namsor_client/api_client'
require 'namsor_client/api_error'
require 'namsor_client/version'
require 'namsor_client/configuration'

# Models
require 'namsor_client/models/api_billing_period_usage_out'
require 'namsor_client/models/api_counter_v2_out'
require 'namsor_client/models/api_key_out'
require 'namsor_client/models/api_period_usage_out'
require 'namsor_client/models/api_plan_out'
require 'namsor_client/models/api_plan_subscription_out'
require 'namsor_client/models/api_plans_out'
require 'namsor_client/models/api_service_out'
require 'namsor_client/models/api_services_out'
require 'namsor_client/models/api_usage_aggregated_out'
require 'namsor_client/models/batch_first_last_name_diasporaed_out'
require 'namsor_client/models/batch_first_last_name_gender_in'
require 'namsor_client/models/batch_first_last_name_gendered_out'
require 'namsor_client/models/batch_first_last_name_geo_in'
require 'namsor_client/models/batch_first_last_name_geo_zipped_in'
require 'namsor_client/models/batch_first_last_name_in'
require 'namsor_client/models/batch_first_last_name_origined_out'
require 'namsor_client/models/batch_first_last_name_phone_coded_out'
require 'namsor_client/models/batch_first_last_name_phone_number_geo_in'
require 'namsor_client/models/batch_first_last_name_phone_number_in'
require 'namsor_client/models/batch_first_last_name_us_race_ethnicity_out'
require 'namsor_client/models/batch_name_match_candidates_out'
require 'namsor_client/models/batch_parsed_full_name_geo_in'
require 'namsor_client/models/batch_parsed_full_name_in'
require 'namsor_client/models/batch_personal_name_gendered_out'
require 'namsor_client/models/batch_personal_name_geo_in'
require 'namsor_client/models/batch_personal_name_geo_out'
require 'namsor_client/models/batch_personal_name_in'
require 'namsor_client/models/batch_personal_name_parsed_out'
require 'namsor_client/models/billing_history_out'
require 'namsor_client/models/billing_info_in_out'
require 'namsor_client/models/classifier_metrics_out'
require 'namsor_client/models/currencies_out'
require 'namsor_client/models/deploy_ui_out'
require 'namsor_client/models/expected_class_metrics_out'
require 'namsor_client/models/first_last_name_diasporaed_out'
require 'namsor_client/models/first_last_name_gender_in'
require 'namsor_client/models/first_last_name_gendered_out'
require 'namsor_client/models/first_last_name_geo_in'
require 'namsor_client/models/first_last_name_geo_zipped_in'
require 'namsor_client/models/first_last_name_in'
require 'namsor_client/models/first_last_name_origined_out'
require 'namsor_client/models/first_last_name_out'
require 'namsor_client/models/first_last_name_phone_coded_out'
require 'namsor_client/models/first_last_name_phone_number_geo_in'
require 'namsor_client/models/first_last_name_phone_number_in'
require 'namsor_client/models/first_last_name_us_race_ethnicity_out'
require 'namsor_client/models/inline_object'
require 'namsor_client/models/invoice_item_out'
require 'namsor_client/models/invoice_out'
require 'namsor_client/models/nam_sor_counter_out'
require 'namsor_client/models/name_match_candidate_out'
require 'namsor_client/models/name_match_candidates_out'
require 'namsor_client/models/parsed_full_name_geo_in'
require 'namsor_client/models/parsed_full_name_in'
require 'namsor_client/models/personal_name_gendered_out'
require 'namsor_client/models/personal_name_geo_in'
require 'namsor_client/models/personal_name_geo_out'
require 'namsor_client/models/personal_name_in'
require 'namsor_client/models/personal_name_parsed_out'
require 'namsor_client/models/romanized_name_out'
require 'namsor_client/models/software_version_out'
require 'namsor_client/models/source_detailed_metrics_out'
require 'namsor_client/models/source_metrics_out'
require 'namsor_client/models/stripe_card_out'
require 'namsor_client/models/stripe_customer_out'
require 'namsor_client/models/system_metrics_out'
require 'namsor_client/models/user_info_out'

# APIs
require 'namsor_client/api/admin_api'
require 'namsor_client/api/chinese_api'
require 'namsor_client/api/personal_api'
require 'namsor_client/api/social_api'

module NamSorClient
  class << self
    # Customize default settings for the SDK using block.
    #   NamSorClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
